stages:
  - build
  - deploy

variables:
  AWS_REGION: "eu-central-1"
  ECR_REPOSITORY_URI: $CI_REGISTRY_IMAGE
  
build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli --break-system-packages
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
    - docker build -t $ECR_REPOSITORY_URI:$CI_COMMIT_SHA .
    - docker push $ECR_REPOSITORY_URI:$CI_COMMIT_SHA
    - docker tag $ECR_REPOSITORY_URI:$CI_COMMIT_SHA $ECR_REPOSITORY_URI:latest
    - docker push $ECR_REPOSITORY_URI:latest
  only:
    - main

deploy_frontend:
  stage: deploy
  script:
    - echo "$SSH_KEY" > /tmp/id_rsa
    - chmod 600 /tmp/id_rsa

    - mkdir -p ~/.ssh
    - ssh-keyscan -H $FRONTEND_EC2_IP >> ~/.ssh/known_hosts
    
    - scp -i /tmp/id_rsa docker-compose.yml $SSH_USER@$FRONTEND_EC2_IP:/home/$SSH_USER/
    - ssh -i /tmp/id_rsa $SSH_USER@$FRONTEND_EC2_IP <<EOF
      cd /home/$SSH_USER/
      sudo apt-get update && sudo apt-get install -y docker-compose-plugin
      docker compose down
      docker compose pull
      docker compose up -d
    EOF
  only:
    - main
  variables:
    FRONTEND_EC2_IP: $CI_JOB_FRONTEND_IP
