stages:
  - build
  - deploy

variables:
  AWS_REGION: "eu-central-1" 
  ECR_REPOSITORY_URI: $CI_REGISTRY_IMAGE
  SSH_USER: ""
  SSH_KEY: ""

build_image:
  stage: build
  script:
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
    - docker build -t $ECR_REPOSITORY_URI:$CI_COMMIT_SHA .
    - docker push $ECR_REPOSITORY_URI:$CI_COMMIT_SHA
  only:
    - master

deploy_backend:
  stage: deploy
  script:
    - scp -i $SSH_KEY docker-compose.yml $SSH_USER@$BACKEND_EC2_IP:/home/$SSH_USER/
    - ssh -i $SSH_KEY $SSH_USER@$BACKEND_EC2_IP <<EOF
      cd /home/$SSH_USER/
      docker-compose down
      docker-compose pull
      docker-compose up -d
      EOF
  only:
    - master
  variables:
    BACKEND_EC2_IP: $CI_JOB_BACKEND_IP
